const status:Record<string,string> = {
    'MOI_TAO': "Hồ sơ mới",
    'CHO_XAC_NHAN_TT1': "Chờ XNTT đợt 1",
    'CHO_VAO_BC_1': "Chờ vào BC1",
    'DANG_TRONG_BC_1': "Đã xếp vào BC1",
    // 'YEU_CAU_RUT_HS': "Đang YC rút hồ sơ",
    'CHO_XN_HOAN_HUY_FN': "Chờ kế toán XN rút HS",
    'CHO_XN_HOAN_HUY_GD': "Chờ GD phê duyệt rút HS",
    'DA_RUT_HS': "Đã rút HS",
    'DANG_YC_DOI_CHO': "Đang yêu cầu đổi chỗ",
    'XAC_NHAN_BC_1': "Đang học",
    // 'YEU_CAU_BAO_LUU_HOC':,
    // 'DANG_BAO_LUU_HOC':,
    'DA_HOC_XONG': "Hoàn thành học",
    'DA_BO_HOC': "Đã bỏ",
    'CHO_XAC_NHAN_TT2': "Chờ XNTT đợt 2",
    'CHO_THI_TN': "Chờ thi TN",
    'TRUOT_TN': 'Trượt Tốt nghiệp',
    'CHO_VAO_BC_2': "Chờ vào BC2",
    // 'YEU_CAU_BAO_LUU_THI':,
    'DANG_BAO_LUU_THI': "Đang bảo lưu",
    'DANG_YC_QUAY_LAI_THI': "Đang yêu cầu quay lại thi",
    'DANG_TRONG_BC_2': "Đang trong BC2",
    // 'XAC_NHAN_BC_2':,
    'THI_TRUOT_LT': "Thi trượt lý thuyết",
    'THI_TRUOT_SH': "Thi trượt sa hình",
    'THI_TRUOT_DT': "Thi trượt đường trường",
    'CHO_XNTT_TL_LT': 'Chờ XNTT thi lại lý thuyết',
    'CHO_XNTT_TL_SH': 'Chờ XNTT thi lại sa hình',
    'CHO_XNTT_TL_DT': 'Chờ XNTT thi lại đường trường',
    'HOAN_THANH': "Đã hoàn thành"
}
export default status